version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install --no-cache-dir poetry poetry-plugin-export
      - poetry export -f requirements.txt -o requirements.txt --without-hashes --without dev
      - pip install --no-cache-dir -r requirements.txt

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: docs/requirements.txt

formats:
  - pdf
